Mobile sniffer
genagain/portfolio pull request #36
Opened 2016-12-23 16:05 UTC by genagain

In this PR, I implemented the mobile sniffer to address #25. If the user is on a mobile device or an iPad, they see a message that prompts them to use a computer.

2016-12-24 14:49 UTC, mikehwagz commented
hey man! this looks good, but there is no need to load the sniffer module in app.js.

```js
// check out the init method in preloader.js

init(req, done) {

  classes.add(config.body, 'is-loading')
  
  ajax.get(`${config.BASE}data/data.json`, {
    success: (object) => {
      window._data = object.data
      done()
    }
  })

  config.infos = sniffer.getInfos()

  this.createDOM()
  
  done()
}
```

This line, `config.infos = sniffer.getInfos()` allows us to access all device information globally.

2016-12-24 14:53 UTC, mikehwagz requested changes
So instead of loading sniffer here, you can just write `if (config.infos.isDevice) {...}`

Additionally, I think it would be cleaner to just `return` after the swap instead of wrapping all those bindings in an `else` statement

2016-12-25 15:51 UTC, genagain commented
Hey man, thanks for the great feedback! I eliminated the else clause and added the return in the if statement in the constructor. I can see why the pre-loader would update the `config.infos` key-value pair with the sniffer info. That being said, in the constructor for the App class `config.infos` was `null` so the new condition for the if statement wasn't working. Because of this, I decided to do the sniffing in config.js and delete the sniffing in the preloader.  I realize this is slightly different to what you suggested. Considering that the height and width of the window is retrieved in `config.js`, I figured it would be okay to do the sniffing in the same place.

2016-12-25 15:58 UTC, mikehwagz approved these changes

2016-12-25 15:58 UTC, merged